-- Schema initialization for MariaDB

CREATE TABLE IF NOT EXISTS uploads (
  id BIGINT NOT NULL AUTO_INCREMENT,
  file_name VARCHAR(512) NOT NULL,
  uploaded_at DATETIME(6) NOT NULL,
  number_of_rows INT NOT NULL,
  number_of_columns INT NOT NULL,
  header_line TEXT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS data_records (
  id BIGINT NOT NULL AUTO_INCREMENT,
  upload_id BIGINT NOT NULL,
  col01 TEXT,
  col02 TEXT,
  col03 TEXT,
  col04 TEXT,
  col05 TEXT,
  col06 TEXT,
  col07 TEXT,
  col08 TEXT,
  col09 TEXT,
  col10 TEXT,
  col11 TEXT,
  col12 TEXT,
  col13 TEXT,
  col14 TEXT,
  col15 TEXT,
  col16 TEXT,
  col17 TEXT,
  col18 TEXT,
  col19 TEXT,
  col20 TEXT,
  col21 TEXT,
  col22 TEXT,
  col23 TEXT,
  col24 TEXT,
  col25 TEXT,
  col26 TEXT,
  col27 TEXT,
  col28 TEXT,
  col29 TEXT,
  col30 TEXT,
  col31 TEXT,
  col32 TEXT,
  col33 TEXT,
  col34 TEXT,
  col35 TEXT,
  col36 TEXT,
  col37 TEXT,
  col38 TEXT,
  col39 TEXT,
  col40 TEXT,
  col41 TEXT,
  col42 TEXT,
  col43 TEXT,
  col44 TEXT,
  col45 TEXT,
  col46 TEXT,
  col47 TEXT,
  col48 TEXT,
  col49 TEXT,
  col50 TEXT,
  col51 TEXT,
  col52 TEXT,
  col53 TEXT,
  col54 TEXT,
  col55 TEXT,
  col56 TEXT,
  col57 TEXT,
  col58 TEXT,
  col59 TEXT,
  col60 TEXT,
  col61 TEXT,
  col62 TEXT,
  col63 TEXT,
  col64 TEXT,
  PRIMARY KEY (id),
  KEY idx_data_records_upload (upload_id),
  KEY idx_data_records_col1 (col01(255)),
  KEY idx_data_records_col2 (col02(255)),
  KEY idx_data_records_col3 (col03(255)),
  CONSTRAINT fk_data_records_upload FOREIGN KEY (upload_id) REFERENCES uploads (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 